import random
import time

phrasal_verbs = {
    "act up": "źle się zachowywać / nie działać poprawnie",
    "add up": "mieć sens / sumować się",
    "agree with": "zgadzać się z (kimś, czymś)",
    "allow for": "brać pod uwagę",
    "answer back": "odpowiadać niegrzecznie",
    "ask out": "zaprosić na randkę",
    "back away": "cofnąć się",
    "back down": "ustąpić, wycofać się",
    "back out": "wycofać się (z umowy, zobowiązania)",
    "back up": "popierać, robić kopię zapasową",
    "bail out": "poratować finansowo",
    "be in for": "mieć przed sobą (coś nieprzyjemnego)",
    "be off": "być nieobecnym / zepsutym (np. jedzenie)",
    "be up to": "kombinować coś / być zdolnym do czegoś",
    "blow up": "eksplodować / wściec się",
    "boil down to": "sprowadzać się do czegoś",
    "break down": "zepsuć się / załamać się",
    "break in": "włamać się",
    "break out": "wybuchnąć (np. wojna, pożar)",
    "break up": "zerwać z kimś / rozdzielić coś",
    "bring about": "spowodować",
    "bring forward": "przyspieszyć (np. termin)",
    "bring up": "poruszyć temat / wychowywać",
    "brush up on": "odświeżyć wiedzę",
    "bump into": "wpaść na kogoś przypadkiem",
    "burn out": "wypalić się zawodowo",
    "call back": "oddzwonić",
    "call off": "odwołać",
    "call on": "odwiedzić / wezwać do odpowiedzi",
    "carry on": "kontynuować",
    "carry out": "przeprowadzać (np. badania)",
    "catch on": "zyskać popularność / załapać",
    "catch up with": "dogonić",
    "check in": "zameldować się",
    "check out": "wymeldować się / sprawdzić coś",
    "chip in": "dorzucić się",
    "clean up": "posprzątać",
    "clear up": "rozjaśnić się (pogoda), wyjaśnić coś",
    "come across": "natknąć się / sprawiać wrażenie",
    "come along": "pojawić się / towarzyszyć",
    "come down with": "zachorować na coś",
    "come out": "wyjść na jaw / ukazać się",
    "come over": "wpaść z wizytą",
    "come round": "odzyskać przytomność / wpaść",
    "come up": "pojawić się",
    "come up with": "wymyślić coś",
    "count on": "liczyć na",
    "crack down on": "rozprawić się z czymś",
    "cut back on": "ograniczyć",
    "cut down on": "zmniejszyć (np. spożycie)",
    "cut off": "odciąć",
    "deal with": "radzić sobie z czymś",
    "do away with": "pozbyć się",
    "do up": "zapiąć / odnowić",
    "dress up": "wystroić się",
    "drop by": "wpaść z wizytą",
    "drop off": "zasnąć / podrzucić kogoś",
    "drop out": "zrezygnować (np. ze studiów)",
    "eat out": "jeść poza domem",
    "end up": "skończyć (np. gdzieś, jako ktoś)",
    "fall apart": "rozpaść się",
    "fall behind": "zalegać / mieć zaległości",
    "fall for": "zakochać się / dać się nabrać",
    "fall out": "pokłócić się",
    "figure out": "zrozumieć coś",
    "fill in": "wypełnić (formularz)",
    "find out": "dowiedzieć się",
    "focus on": "skupić się na",
    "follow through": "dokończyć",
    "get ahead": "robić postępy",
    "get along with": "dogadywać się z",
    "get around": "poruszać się / rozprzestrzeniać się",
    "get away": "uciec",
    "get away with": "ujść na sucho",
    "get back": "wrócić",
    "get back at": "zemścić się",
    "get by": "radzić sobie (finansowo)",
    "get down to": "zabrać się do",
    "get in": "przybyć / wsiąść",
    "get off": "wysiąść / zejść z czegoś",
    "get on": "wsiąść / dogadywać się",
    "get out": "wydostać się",
    "get over": "przeboleć, dojść do siebie",
    "get rid of": "pozbyć się",
    "get through": "przetrwać coś / dodzwonić się",
    "give away": "rozdawać / zdradzić (tajemnicę)",
    "give in": "poddawać się",
    "give up": "zrezygnować",
    "go after": "ścigać kogoś / dążyć do czegoś",
    "go ahead": "śmiało, zaczynać",
    "go back on": "złamać obietnicę",
    "go for": "spróbować czegoś",
    "go off": "zepsuć się / wybuchnąć / zadzwonić (budzik)",
    "go on": "kontynuować",
    "go over": "przejrzeć / omówić",
    "go through": "przejść przez coś (trudnego)",
    "grow up": "dorastać",
    "hand in": "oddać (pracę)",
    "hand out": "rozdawać",
    "hang on": "poczekać",
    "hang out": "spędzać czas (z kimś)",
    "hold back": "powstrzymywać",
    "hold on": "czekać",
    "hold up": "opóźniać / napaść (z bronią)",
    "iron out": "wygładzić (problemy, różnice)",
    "keep at": "nie poddawać się",
    "keep on": "kontynuować",
    "keep up": "nadążać",
    "kick off": "rozpocząć",
    "lay off": "zwolnić z pracy",
    "leave out": "pominąć",
    "let down": "zawieść",
    "let in": "wpuścić",
    "let out": "wypuścić",
    "live up to": "sprostać (oczekiwaniom)",
    "look after": "opiekować się",
    "look ahead": "patrzeć w przyszłość",
    "look back on": "wspominać",
    "look down on": "pogardzać",
    "look for": "szukać",
    "look forward to": "nie móc się doczekać",
    "look into": "zbadać, przyjrzeć się",
    "look out": "uważać",
    "look up": "sprawdzać (w słowniku)",
    "look up to": "podziwiać",
    "make for": "kierować się w stronę",
    "make out": "dostrzec / zrozumieć",
    "make up": "zmyślić / pogodzić się / nadrobić",
    "miss out": "przegapić",
    "narrow down": "zawęzić",
    "pass away": "umrzeć",
    "pass out": "zemdleć",
    "pay back": "spłacić",
    "pick on": "czepiać się",
    "pick out": "wybrać",
    "pick up": "podnieść / odebrać / nauczyć się mimochodem",
    "point out": "zwrócić uwagę",
    "pull over": "zjechać na pobocze",
    "put aside": "odkładać",
    "put off": "odkładać na później / zniechęcać",
    "put on": "zakładać / przybrać na wadze",
    "put out": "zgasić (ogień)",
    "put up with": "znosić coś",
    "run away": "uciec",
    "run into": "wpaść na kogoś",
    "run out of": "skończyć się",
    "set off": "wyruszyć",
    "set up": "założyć, zorganizować",
    "show off": "popisywać się",
    "shut down": "zamknąć (firmę, komputer)",
    "sort out": "rozwiązać (problem)",
    "speak up": "mówić głośniej",
    "stand by": "wspierać kogoś",
    "stand out": "wyróżniać się",
    "stand up for": "bronić czegoś",
    "stick to": "trzymać się czegoś",
    "take after": "być podobnym do",
    "take apart": "rozebrać (na części)",
    "take away": "zabrać",
    "take back": "cofnąć (słowa)",
    "take down": "zapisać / zburzyć",
    "take in": "przyjąć / pojąć",

    "take off": "wystartować / zdjąć ubranie",
    "take on": "podjąć się",
    "take out": "wyjąć / zabrać kogoś gdzieś",
    "take over": "przejąć kontrolę",
    "tear up": "podrzeć",
    "think over": "przemyśleć",
    "throw away": "wyrzucić",
    "try on": "przymierzyć",
    "turn down": "odrzucić / ściszyć",
    "turn into": "zamienić się w",
    "turn off": "wyłączyć / zniechęcić",
    "turn on": "włączyć",
    "turn up": "pojawić się / podgłośnić",      
    "wake up": "obudzić się",
    "walk out on": "opuścić (kogoś)",
    "warm up": "rozgrzać się",
    "watch out": "uważać",
    "wear off": "ustąpić",
    "wear out": "zniszczyć / zmęczyć",
    "work out": "ćwiczyć / rozwiązać",
    "wrap up": "zakończyć / owinąć",
    "write down": "zapisać"
}


def quiz():
    while True:
        verb = random.choice(list(phrasal_verbs.keys()))
        print(f"\n{verb}")
        time.sleep(4)
        print(f"{phrasal_verbs[verb]}")
        time.sleep(2)

if __name__ == "__main__":
    quiz()

